export const clickBurger = 'APP/OPEN_CLOSE_BURGER'
export const clickVideoModal = 'APP/OPEN_CLOSE_VIDEO_MODAL'
export const scrollToElement = 'APP/SCROLL_TO_ELEMENT'
export const slideToRedux = 'SWIPER/SLIDE_TO'
export const clickModal = 'APP/OPEN_CLOSE_MODAL'